# Generated by Django 2.0 on 2017-12-25 13:21

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datetime', django_jalali.db.models.jDateTimeField()),
                ('Sex', models.CharField(default='M', max_length=20)),
                ('Age', models.CharField(default='None', max_length=20)),
                ('QoProduct', models.IntegerField(default=0)),
                ('QoDesign', models.IntegerField(default=0)),
                ('QoResponse', models.IntegerField(default=0)),
                ('QoDelivery', models.IntegerField(default=0)),
                ('QoPersonality', models.IntegerField(default=0)),
                ('QoDecor', models.IntegerField(default=0)),
                ('QoAmount', models.IntegerField(default=0)),
                ('QoShape', models.IntegerField(default=0)),
            ],
        ),
    ]
