# Generated by Django 2.0 on 2017-12-25 13:30

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='Datetime',
        ),
        migrations.AddField(
            model_name='answer',
            name='Date',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
