# Generated by Django 2.0 on 2017-12-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20171225_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='Comment',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
