# Generated by Django 2.0 on 2017-12-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_answer_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='Time',
            field=models.TimeField(null=True),
        ),
    ]
